name: book_app
description: A Flutter EPUB reader with Kindle-like functionality
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  file_picker: ^8.0.5
  epub_view: ^3.2.0
  shared_preferences: ^2.2.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  path_provider: ^2.1.1
  permission_handler: ^11.0.1
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/fonts/
    
  fonts:
    - family: Bookerly
      fonts:
        - asset: assets/fonts/Bookerly-Regular.ttf
        - asset: assets/fonts/Bookerly-Bold.ttf
          weight: 700
        - asset: assets/fonts/Bookerly-Italic.ttf
          style: italic
        - asset: assets/fonts/Bookerly-BoldItalic.ttf
          weight: 700
          style: italic
